# Site settings
title: Sunright
SEOTitle: Sunright
header-img: img/head/index-one.jpg
email: isostay@gmail.com
description: "There is no garden without its weeds."
keyword: "Internet, AI, meta, web3, softwares, easy tools, web tools, future research, human research"
url: "https://xion.eu.org"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/Sostay/Sostay.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Goals determine what you're going to be!"
sidebar-avatar: /pwa/icons/pwa_icon_128.png      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:     qiubaiying
# zhihu_username:     qiubaiying
# github_username:    qiubaiying
# facebook_username:  baiying.qiu.7
# jianshu_username:   e71990ada2fd
# twitter_username:   qiubaiying

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown #<默认值：kramdown, 可选kramdown,rdiscount,redcarpet>
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: qiubaiying

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: 8d0f5197310e3854dc12                            #生成的clientID
  clientSecret: 5b4a563e1929d98f98afc29cb36054bf98180d6d    #生成的clientSecret
  repo: Sostay.github.io    #仓库名称
  owner: Sostay  #github用户名
  admin: Xion.
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
# ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
# ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
# ga_domain: auto               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto





# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#FFFFFF"
service-worker: true



# 友情链接，请尽量不要删除，谢谢！
friends: [
    {
        title: "星球国际语",
        href: "https://globien.gitee.io"
    },{
        title: "星球语互动社区",
        href: "https://tieba.baidu.com/f?kw=%E6%A0%BC%E7%BD%97%E6%AF%94%E8%A8%80&fr=home"
    },{
        title: "知乎：人造国际语",
        href: "https://zhuanlan.zhihu.com/Artificial-International-Language"
    }
]
